extractor:
  nb_samp: 64600
  first_conv: 128
  filts: [70, [1, 32], [32, 32], [32, 64], [64, 64]]
  gat_dims: [64, 32]
  pool_ratios: [0.5, 0.7, 0.5, 0.5]
  temperatures: [2.0, 2.0, 100.0, 100.0]
mmd_model:
  is_xx_zero: false
  is_yy_zero: false
  coeff_xy: 2.0
  transformer_flag: true
  num_hidden_layers: 1
  num_attention_heads: 4
  num_mlp: 1
  in_dim: 1472
  token_num: 27
  hid_dim: 512
  out_dim: 300
  dropout: 0.4